### ISSUE TITLE
how about the performance compare with CPU?

### ISSUE THREAD

**Issue by caofx0418** [lrw04/llama2.c-to-ncnn#1]
hi, how about the performance compare with CPU?

thank you!

**Comment by lrw04** [comment]
I ran it on Apple M2 with the 13B foundational model, and the generation time of the first 100 tokens average out to be 699 ms/token. This is slower than llama.cpp since for example it doesn't have flash attention for now. If there is demand, I might tinker with it a bit more to potentially add it to the converter.

**Comment by lrw04** [comment]
Another note: the LinearInt8 layer in the output model has only ARM NEON acceleration for now, so everything ran on the CPU.

**Comment by caofx0418** [comment]
> Another note: the LinearInt8 layer in the output model has only ARM NEON acceleration for now, so everything ran on the CPU.

thank you for your reply, do you have any plan to write GPU instrinct for LinearInt8 layer?

**Comment by lrw04** [comment]
I don't plan to write GPU code before I finish my current project.
